/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.mat.tabacos.modelo.dao.sql;

/**
 *
 * @author MTI Agustin Romero Mata
 */
public interface AutorizarSolicitudSQL {

    String SQL_SELECT_NEXTID_ARCHIVO = "SELECT TBCQ_ARCHIVO.NEXTVAL FROM DUAL";
    String SQL_SELECT_AUTORIZACIONCB = "SELECT IDSPAUTORIZA, DESCSPAUTORIZA "
            + "FROM TBCC_SPAUTORIZA";
    String SQL_SELECT_RESOLUCIONCB = "SELECT IDESTRESOLUCION, DESCESTRESOLUCION "
            + "FROM TBCC_ESTRESOLUCION";

    String SQL_UPDATE_RESOLUCION = "UPDATE TBCT_RESOLUCION SET IDESTRESOLUCION = ? , FECRESOLUCION = ? , IDSPAUTORIZA = ? \n"
            + "WHERE IDSOLICITUD = ?";

    String SQL_UPDATE_RESOLUCION2 = "UPDATE TBCT_RESOLUCION SET IDSPAUTORIZA = ?, "
            + "FECRESOLUCION = ?, FOLIOINICIAL = ?, FOLIOFINAL = ? WHERE IDSOLICITUD = ?";

    String SQL_UPDATE_SOLICITUD = "UPDATE TBCT_SOLICITUD SET CANTAUTORIZADA = ? "
            + "WHERE IDSOLICITUD = ?";

    String SQL_INSERT_ARCHIVO = "INSERT INTO TBCT_ARCHIVO(IDARCHIVO, RUTAARCHIVO, "
            + "FECREGISTRO, IDSOLICITUD, NUMLINEA, FECHAINICIO, FECHAFIN, IDTIPOARCHIVO"
            + ", NUMOOFICIO) "
            + "VALUES(?,?,?,?,?,?,?,?,?)";

    String SQL_SELECT_AUTSOLICITUD = "SELECT TSOL.IDSOLICITUD, TTAB.RFC, "
            + "TTAB.RAZONSOCIAL, TSOL.CANTSOLICITADA, "
            + "TO_CHAR(TSOL.FECSOLICITUD, 'DD/MM/YYYY') AS FECSOLICITUD, "
            + "TEST.IDESTATUS, TEST.DESCESTRESOLUCION RESOLUCION  "
            + "FROM TBCT_SOLICITUD TSOL, TBCT_RESOLUCION TRES, "
            + "TBCC_ESTRESOLUCION TEST, TBCP_TABACALERA TTAB, TBCA_TBC_PROV TTP "
            + "WHERE TEST.IDESTRESOLUCION = TRES.IDESTRESOLUCION "
            + "AND TRES.IDSOLICITUD = TSOL.IDSOLICITUD "
            + "AND TSOL.IDTBCPROV = TTP.IDTBCPROV "
            + "AND TTP.IDTABACALERA = TTAB.IDTABACALERA "
            + "AND TRES.IDESTRESOLUCION = 1 ";

    String SQL_SELAUTSOLICITUDXAUT = "SELECT TSOL.IDSOLICITUD, TTAB.RFC, "
            + "TTAB.RAZONSOCIAL, TSOL.CANTSOLICITADA, TSOL.FECSOLICITUD, "
            + "TEST.IDESTATUS, TSOL.CANTAUTORIZADA, TRES.FECRESOLUCION,"
            + "TRES.IDSPAUTORIZA, TTAB.RAZONSOCIAL, TARC.RUTAARCHIVO, "
            + "TARC.NUMOOFICIO "
            + "FROM TBCT_ARCHIVO TARC, TBCT_SOLICITUD TSOL, TBCT_RESOLUCION TRES, "
            + "TBCC_ESTRESOLUCION TEST, TBCP_TABACALERA TTAB, TBCA_TBC_PROV TTP "
            + "WHERE TARC.IDSOLICITUD = TSOL.IDSOLICITUD "
            + "AND TEST.IDESTRESOLUCION = TRES.IDESTRESOLUCION "
            + "AND TRES.IDSOLICITUD = TSOL.IDSOLICITUD "
            + "AND TSOL.IDTBCPROV = TTP.IDTBCPROV "
            + "AND TTP.IDTABACALERA = TTAB.IDTABACALERA ";

    String SQL_SELECT_AUTSOLICITUD_RFC = "AND TTAB.RFC = ?";
    String SQL_SELECT_AUTSOLICITUD_FECHA = "AND TSOL.FECSOLICITUD BETWEEN ? AND ?";
    String SQL_SELECT_AUTSOLICITUD_FOLIO = "AND TSOL.IDSOLICITUD = ?";
    String SQL_SELECT_AUTSOLICITUD_RSOCIAL = "AND TTAB.RAZONSOCIAL = ?";

    String SQL_INSERT_CODIGO2015
            = "INSERT INTO TBCT_CODIGO0(FOLIO,CODIGO,IDSOLICITUD) VALUES(?,?,?)";
    String SQL_INSERT_CODIGO2016
            = "INSERT INTO TBCT_CODIGO1(FOLIO,CODIGO,IDSOLICITUD) VALUES(?,?,?)";
    String SQL_INSERT_CODIGO2017
            = "INSERT INTO TBCT_CODIGO2(FOLIO,CODIGO,IDSOLICITUD) VALUES(?,?,?)";
    String SQL_INSERT_CODIGO2018
            = "INSERT INTO TBCT_CODIGO3(FOLIO,CODIGO,IDSOLICITUD) VALUES(?,?,?)";
    String SQL_INSERT_CODIGO2019
            = "INSERT INTO TBCT_CODIGO4(FOLIO,CODIGO,IDSOLICITUD) VALUES(?,?,?)";
    String SQL_MAXFOLIO_CODIGO0 = "select max(FOLIO) from TBCT_CODIGO0";
    String SQL_MAXFOLIO_CODIGO1 = "select max(FOLIO) from TBCT_CODIGO1";
    String SQL_MAXFOLIO_CODIGO2 = "select max(FOLIO) from TBCT_CODIGO2";
    String SQL_MAXFOLIO_CODIGO3 = "select max(FOLIO) from TBCT_CODIGO3";
    String SQL_MAXFOLIO_CODIGO4 = "select max(FOLIO) from TBCT_CODIGO4";
}
