//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.11 at 05:54:08 PM CST 
//
package mx.gob.sat.mat.tabacos.ws.dto;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the mx.gob.sat.mat.tabacos.ws.dto package.
 * <p>An ObjectFactory allows you to programatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: mx.gob.sat.mat.tabacos.ws.dto
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TBCSlcCodSeg.Solicitud }
     *
     * @return 
     */
    public Solicitud createTBCSlcCodSegSolicitud() {
        return new Solicitud();
    }

    /**
     * Create an instance of {@link TBCRetroInfo.Destruccion }
     *
     * @return 
     */
    public Destruccion createTBCRetroInfoDestruccion() {
        return new Destruccion();
    }

    /**
     * Create an instance of {@link TBCRetroInfo.CodigoFalso }
     *
     * @return 
     */
    public CodigosNoValidos createTBCRetroInfoCodigoFalso() {
        return new CodigosNoValidos();
    }

    /**
     * Create an instance of {@link TBCAcuseRetroInfo.Acuse }
     *
     * @return 
     */
    public AcuseRetro createTBCAcuseRetroInfoAcuse() {
        return new AcuseRetro();
    }

    /**
     * Create an instance of {@link RangoCodigosSeguridad }
     *
     * @return 
     */
    public RangoCodigosSeguridad createRangoCodigosSeguridad() {
        return new RangoCodigosSeguridad();
    }

    /**
     * Create an instance of {@link TBCRespDescarga }
     *
     * @return 
     */
    public TBCRespDescarga createTBCRespDescarga() {
        return new TBCRespDescarga();
    }

    /**
     * Create an instance of {@link TBCRespConsulFolio }
     *
     * @return 
     */
    public TBCRespConsulFolio createTBCRespConsulFolio() {
        return new TBCRespConsulFolio();
    }

    /**
     * Create an instance of {@link TBCRespConsulFolio.Folio }
     *
     * @return 
     */
    public Folio createTBCRespConsulFolioFolio() {
        return new Folio();
    }

    /**
     * Create an instance of {@link TBCAcuRboSlc.Acuse }
     *
     * @return 
     */
    public Acuse createTBCAcuRboSlcAcuse() {
        return new Acuse();
    }

    /**
     * Create an instance of {@link TBCConsulFolio }
     *
     * @return 
     */
    public TBCConsulFolio createTBCConsulFolio() {
        return new TBCConsulFolio();
    }

    /**
     * Create an instance of {@link TBCRetroInfo.Produccion }
     *
     * @return 
     */
    public Produccion createTBCRetroInfoProduccion() {
        return new Produccion();
    }

    /**
     * Create an instance of {@link TBCRespConsulFolio.Folio.Archivos }
     *
     * @return 
     */
    public Archivos createTBCRespConsulFolioFolioArchivos() {
        return new Archivos();
    }

    /**
     * Create an instance of {@link TBCAcuRboSlc }
     *
     * @return 
     */
    public TBCAcuRboSlc createTBCAcuRboSlc() {
        return new TBCAcuRboSlc();
    }

    /**
     * Create an instance of {@link TBCRetroInfo }
     *
     * @return 
     */
    public TBCRetroInfo createTBCRetroInfo() {
        return new TBCRetroInfo();
    }

    /**
     * Create an instance of {@link TBCConsulFolio.Folios }
     *
     * @return 
     */
    public Folios createTBCConsulFolioFolios() {
        return new Folios();
    }

    /**
     * Create an instance of {@link TBCSlcCodSeg }
     *
     * @return 
     */
    public TBCSlcCodSeg createTBCSlcCodSeg() {
        return new TBCSlcCodSeg();
    }

    /**
     * Create an instance of {@link TBCAcuseRetroInfo }
     *
     * @return 
     */
    public TBCAcuseRetroInfo createTBCAcuseRetroInfo() {
        return new TBCAcuseRetroInfo();
    }

    /**
     * Create an instance of {@link TBCSolDescarga }
     *
     * @return 
     */
    public TBCSolDescarga createTBCSolDescarga() {
        return new TBCSolDescarga();
    }
}
