/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.gob.sat.mat.tabacos.persistence;

/**
 *
 * @author platon
 */
public interface ReportesFields {
    String RFC = "RFC";
    
    String FIELD_PROVEEDOR_RFC = RFC;    
    String FIELD_PROVEEDOR_FECHA = "FECMOVIMIENTO";
    
    String FIELD_CODIGO_NUMEROCODIGO = "CODIGO";    
    String FIELD_CODIGO_FECHA = "FECCAPTURA";
    String FIELD_CODIGO_FOLIOFINAL = "FOLIOFINAL";    
    String FIELD_CODIGO_FOLIOINICIAL = "FOLIOINICIAL";
    String FIELD_CODIGO_RFC = RFC;
       
    String FIELD_CODFALSO_FECHA = "FECREGISTRO";
        
    String FIELD_MARCA_MARCA = "NOMMARCA";
    
    String FIELD_HISTORICO_FOLIO = "FOLIO";
    String FIELD_HISTORICO_RFC = RFC;
    String FIELD_HISTORICO_CONTRIBUYENTE = "CONTRIBUYENTE";
    String FIELD_HISTORICO_CANTIDAD = "CANTSOLICITADA";    
    String FIELD_HISTORICO_FECHA = "FECSOLICITUD";
    String FIELD_HISTORICO_PAS = "PAS";
    
    String FIELD_REGISTRO_LOTE = "NUMLOTE";
    String FIELD_REGISTRO_PLANTA = "NOMPLANTA";
    String FIELD_REGISTRO_CANTIDAD = "CANTPRODUCIDA";
    String FIELD_REGISTRO_PROVEEDOR = "PROVEEDOR";
    String FIELD_REGISTRO_CONTRIBUYENTE = "TABACALERA";
    String FIELD_REGISTRO_PAIS = "PAIS";
    String FIELD_REGISTRO_MAQUINARIA = "DESCMAQUINAPROD";
    String FIELD_REGISTRO_ORIGEN = "ORIGEN";
    String FIELD_REGISTRO_LINEA = "LINEAPRODUCCION";
    String FIELD_REGISTRO_FECHA = "FECPRODUCCION";
    String FIELD_REGISTRO_SOLICITUD = "IDSOLICITUD";
    
    String FIELD_DESPERDICIOS_MARCA = "NOMMARCA";
    String FIELD_DESPERDICIOS_PLANTA = "NOMPLANTA";
    String FIELD_DESPERDICIOS_CANTIDAD_AUTORIZADA = "CANTAUTORIZADA";
    String FIELD_DESPERDICIOS_ORIGEN = "ORIGEN";
    String FIELD_DESPERDICIOS_MAQUINARIA = "DESCMAQUINAPROD";
    String FIELD_DESPERDICIOS_LOTE = "NUMLOTE";
    String FIELD_DESPERDICIOS_FECHA = "FECPRODUCCION";
    String FIELD_DESPERDICIOS_CCIGARROS = "CANTCIGARROS";
    String FIELD_DESPERDICIOS_CPRODUCIDA = "CANTPRODUCIDA";
    String FIELD_DESPERDICIOS_FOLIOINICIAL = "FOLIOINICIAL";
    String FIELD_DESPERDICIOS_FOLIOFINAL = "FOLIOFINAL";    
    
    String FIELD_SUBMARCASCB_IDSUBMARCA = "IDSUBMARCA";
    String FIELD_SUBMARCASCB_NOMBRE = "NOMBRE";
    
    String FIELD_MARCASCB_IDMARCA = "IDMARCA";
    String FIELD_MARCASCB_NOMBRE = "NOMBRE";
    
    String FIELD_CODIGOSCB_IDTIPO = "IDTIPO";
    String FIELD_CODIGOSCB_NOMBRE = "NOMBRE";
    
    String FIELD_PROVEEDORESCB_IDPROVEEDOR = "IDPROVEEDOR";
    String FIELD_PROVEEDORESCB_RAZONSOCIAL = "RAZONSOCIAL";
    
    String FIELD_CONTRIBUYENTESCB_IDCONTRIBUYENTES = "IDCONTRIBUYENTES";
    String FIELD_CONTRIBUYENTESCB_RFC = RFC; 
    
    String FIELD_CONTRIBUYENTE_FECHAMOD = "FECMOVIMIENTO";
    String FIELD_CONTRIBUYENTE_RFC = RFC;   
}
