package mx.gob.sat.mat.tabacos.modelo.dao;

import java.util.List;
import mx.gob.sat.mat.tabacos.modelo.dto.Planta;
import mx.gob.sat.mat.tabacos.modelo.dto.ProduccionCigarros;
import mx.gob.sat.mat.tabacos.modelo.dto.reportes.ReporteDesperdiciosDTO;
import mx.gob.sat.mat.tabacos.modelo.dto.reportes.ReporteProduccion;
import mx.gob.sat.mat.tabacos.modelo.dto.tipo.TipoRetro;
import mx.gob.sat.mat.tabacos.modelo.exceptions.ProduccionDaoException;

/**
 *
 * @author Ing Salvador Pocteco Saldaña
 */
public interface ProduccionCigarrosDao {

    String SQL_ORDER_IDPRODCIGARRO = "ORDER BY TBCT_PRODCIGARRO.IDPRODCIGARRO";
    String SQL_ORDER_RAZON_SOCIAL = "ORDER BY TBCT_PRODCIGARRO.IDPRODCIGARRO";

    String SQL_SELECT_NEXTID_PRODUCCION = "SELECT TBCQ_PRODCIGARRO.NEXTVAL FROM DUAL";
    String SQL_SELECT_NEXTID_TIPO_RETRO = "SELECT TBCQ_TIPORETRO.NEXTVAL FROM DUAL";

    String SQL_SELECT_PLANTAS = "SELECT IDPLANTA, NOMPLANTA FROM TBCT_PLANTA "
            + "WHERE IDTABACALERA = ? "
            + "AND IDESTATUS = 1\n"
            + "ORDER  BY NOMPLANTA";

    String SQL_SELECT_TIPO_RETRO = "SELECT IDTIPORETRO, DESCTIPORETRO  FROM TBCC_TIPORETRO ORDER BY DESCTIPORETRO";

    String SQL_INSERT_PRODUCCION_CIGARROS = "INSERT INTO TBCT_PRODCIGARRO "
            + "(IDPRODCIGARRO, IDMARCA, DESCMAQUINAPROD, NUMLOTE, FECIMPORTACION, FECPRODUCCION, IDPAISORIGEN, DESCPAISORIGEN, CANTPRODUCIDA, IDPLANTA) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    String SQL_INSERT_DESPERDICIOS_DESTRUCCION = "INSERT INTO TBCT_PRODCIGARRO "
            + "(IDPRODCIGARRO, IDMARCA, DESCMAQUINAPROD, NUMLOTE, FECPRODUCCION, IDPAISORIGEN, DESCPAISORIGEN, CANTCIGARROS, CANTPRODUCIDA, IDPLANTA, IDTIPORETRO) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    String SQL_CONSULTA_DATOS_REPORTE_DESPERDICIOS = "SELECT\n"
            + "TBCT_MARCA.NOMMARCA AS NOMMARCA,\n"
            + "TBCT_PLANTA.NOMPLANTA AS NOMPLANTA,\n"
            + "TBCT_PRODCIGARRO.CANTPRODUCIDA AS CANTPRODUCIDA,\n"
            + "TBCT_PRODCIGARRO.DESCPAISORIGEN AS DESCPAISORIGEN,\n"
            + "TBCT_PRODCIGARRO.DESCMAQUINAPROD AS DESCMAQUINAPROD,\n"
            + "TBCT_PRODCIGARRO.NUMLOTE AS NUMLOTE,\n"
            + "TBCT_PRODCIGARRO.FECPRODUCCION AS FECPRODUCCION,\n"
            + "TBCT_PRODCIGARRO.CANTCIGARROS AS CANTCIGARROS,\n"
            + "TBCT_PRODCIGARRO.IDPRODCIGARRO AS IDPRODCIGARRO\n"
            + "FROM TBCT_PRODCIGARRO\n"
            + "INNER JOIN TBCT_MARCA ON TBCT_PRODCIGARRO.IDMARCA = TBCT_MARCA.IDMARCA \n"
            + "INNER JOIN TBCT_PLANTA ON TBCT_PRODCIGARRO.IDPLANTA = TBCT_PLANTA.IDPLANTA\n"
            + "INNER JOIN TBCP_TABACALERA ON TBCT_PLANTA.IDTABACALERA = TBCP_TABACALERA.IDTABACALERA\n"
            + "INNER JOIN TBCP_TABACALERA ON TBCT_MARCA.IDTABACALERA = TBCP_TABACALERA.IDTABACALERA\n"
            + "INNER JOIN TBCT_RANGOFOLIO ON TBCT_PRODCIGARRO.IDPRODCIGARRO = TBCT_RANGOFOLIO.IDPRODCIGARRO\n"
            + "WHERE TBCT_PRODCIGARRO.IDTIPORETRO IS NOT NULL \n"
            + "AND \n";

    String SQL_CONSULTA_DATOS_REPORTE_DESPERDICIOS_POR_RFC = "TBCP_TABACALERA.RFC = ? \n"
            + SQL_ORDER_IDPRODCIGARRO;

    String SQL_CONSULTA_DATOS_REPORTE_DESPERDICIOS_POR_FECHAS = "TBCT_PRODCIGARRO.FECPRODUCCION BETWEEN ? AND ? \n"
            + SQL_ORDER_IDPRODCIGARRO;

    String SQL_CONSULTA_DATOS_REPORTE_PRODUCCION = "SELECT\n"
            + "TBCT_PRODCIGARRO.IDPRODCIGARRO AS IDPRODCIGARRO,\n"
            + "TBCP_TABACALERA.IDTABACALERA AS IDTABACALERA,\n"
            + "TBCT_PROVEEDOR.IDPROVEEDOR AS IDPROVEEDOR,\n"
            + "TBCP_TABACALERA.RFC AS RFC,\n"
            + "TBCT_PROVEEDOR.RAZONSOCIAL AS RAZONSOCIALPROV,\n"
            + "TBCP_TABACALERA.RAZONSOCIAL AS RAZONSOCIALTAB,\n"
            + "TBCT_PRODCIGARRO.NUMLOTE AS NUMLOTE,\n"
            + "TBCT_PLANTA.NOMPLANTA AS NOMPLANTA,\n"
            + "TBCT_PRODCIGARRO.CANTPRODUCIDA AS CANTPRODUCIDA,\n"
            + "TBCT_PRODCIGARRO.DESCMAQUINAPROD AS DESCMAQUINAPROD,\n"
            + "TBCT_PRODCIGARRO.DESCPAISORIGEN AS DESCPAISORIGEN,\n"
            + "TBCT_PRODCIGARRO.LINEAPRODUCCION AS LINEAPRODUCCION\n"
            + "FROM TBCT_PRODCIGARRO \n"
            + "INNER JOIN TBCT_PLANTA ON TBCT_PRODCIGARRO.IDPLANTA = TBCT_PLANTA.IDPLANTA\n"
            + "INNER JOIN TBCP_TABACALERA ON TBCT_PLANTA.IDTABACALERA = TBCP_TABACALERA.IDTABACALERA\n"
            + "INNER JOIN TBCA_TBC_PROV ON TBCP_TABACALERA.IDTABACALERA = TBCA_TBC_PROV.IDTABACALERA\n"
            + "INNER JOIN TBCT_PROVEEDOR ON TBCT_PROVEEDOR.IDPROVEEDOR = TBCA_TBC_PROV.IDPROVEEDOR\n"
            + "INNER JOIN TBCT_RANGOFOLIO ON TBCT_PRODCIGARRO.IDPRODCIGARRO = TBCT_RANGOFOLIO.IDPRODCIGARRO\n"
            + "INNER JOIN TBCT_RESOLUCION ON TBCT_RESOLUCION.IDRESOLUCION = TBCT_RANGOFOLIO.IDRESOLUCION\n"
            + "INNER JOIN TBCT_SOLICITUD ON TBCT_SOLICITUD.IDSOLICITUD = TBCT_RESOLUCION.IDSOLICITUD\n"
            + "INNER JOIN TBCC_ESTRESOLUCION ON  TBCT_RESOLUCION.IDESTRESOLUCION = TBCC_ESTRESOLUCION.IDESTRESOLUCION\n"
            + "WHERE TBCT_PRODCIGARRO.IDTIPORETRO IS NULL\n"
            + "AND TBCC_ESTRESOLUCION.IDESTRESOLUCION = 5 \n"
            + "AND \n";

    String SQL_CONSULTA_DATOS_REPORTE_PRODUCCION_POR_RFC = "TBCP_TABACALERA.RFC = ?\n";

    String SQL_CONSULTA_DATOS_REPORTE_PRODUCCION_POR_FECHAS = "TBCT_PRODCIGARRO.FECPRODUCCION BETWEEN ? AND ?\n";

    String SQL_CONSULTA_REPORTE_PRODUCCION_RAZON_SOCIAL = "AND TBCT_PROVEEDOR.IDPROVEEDOR = ? \n";

    List<Planta> selectedPlantas(Long idTabacalera) throws ProduccionDaoException;

    ProduccionCigarros guardaProduccion(ProduccionCigarros produccion) throws ProduccionDaoException;

    List<TipoRetro> selectedTipoRetro() throws ProduccionDaoException;

    ProduccionCigarros guardarDestruccion(ProduccionCigarros produccion) throws ProduccionDaoException;

    List<ReporteProduccion> consultaReporteProduccion(ReporteProduccion reporteProduccion) throws ProduccionDaoException;

    List<ReporteDesperdiciosDTO> consultaReporteDesperdicios(ReporteDesperdiciosDTO reporteDesperdicios, boolean rfcExiste) throws ProduccionDaoException;

}
